name: On New Issue
run-name: Issue Processor

on:
  issues:
    types: [opened]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install smartsheet-python-sdk

      - name: Run issue processing script
        run: |
          if [[ -f "./nsc-events-nextjs/post-issue-smartsheet.py" ]]; then
            python ./nsc-events-nextjs/post-issue-smartsheet.py "${{ github.event.issue.title }}" "${{ github.event.issue.body }}" "${{ github.event.issue.html_url }}"
          elif [[ -f "./nsc-events-nestjs/post-issue-smartsheet.py" ]]; then
            python ./nsc-events-nestjs/post-issue-smartsheet.py "${{ github.event.issue.title }}" "${{ github.event.issue.body }}" "${{ github.event.issue.html_url }}"
          else
            echo "Issue processing script not found"
            exit 1
          fi
        env:
          SMARTSHEET_ACCESS_TOKEN: # replace me with your token
          SHEET_ID: # replace me with your sheet id
